spring:
  datasource:
    url: jdbc:postgresql://localhost/spring_jwt
    username: ${PSQL_USER}
    password: ${PSQL_PASSWD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
application:
  security:
    jwt:
      secret-key: 58ca0bb1da817b1586b823012a223acac9810141866b44cf544b8e62bf0fade8
      access-token-expiration: 86400000
      refresh-token-expiration: 604800000